### ISSUE TITLE
flow-link

### ISSUE THREAD

**Issue by sparkyspider** [windflow-io/EternalEngine#24]
Make sure flow-link carries ?host=www.example.com across pages. (should check query parameters to see if we're fudging a link and add it to our own query parameters as part of the link.

**Comment by maoberlehner** [comment]
What is the use case for this? Can't we do this via an environment variable instead? Don't love to implement any extra logic in the client which is only for development.
Also, if I understand it correctly, this would enable our users to hijack other sites and serve them from their domain.

**Comment by sparkyspider** [comment]
Hi @maoberlehner, okay, I have a better idea. Let's strip it off and rather have users add hosts to their /etc/hosts (and create aliases)

**Comment by sparkyspider** [comment]
https://github.com/windflow-io/EternalEngine/commit/17804433e584e6a16db46b22fe50663a7931bb65
