### ISSUE TITLE
Components API

### ISSUE THREAD

**Issue by maoberlehner** [windflow-io/EternalEngine#25]
First of all, I think there might be a little bit of confusion between our views on this because for me there clearly should be two endpoints and what you describe reads to me as you want only one.

To me the following would be the ideal setup:

API endpoint: `/api/components/ComponentId`
- Namespace is determined via "Host" request header (or via env variable in dev environment), frontend does not care about that.
- ID can be anything you want as long as it is globally unique, frontend cares only about uniqueness.
- Used for `fetch(ENDPOINT)`.

Asset endpoint: `/components/ComponentId`
- Used for `import MyComponent from '/components/ComponentId'`.

Why two endpoints?
- Cleaner: `import MyComponent from '/api/...'` looks very weird to me. To me an API is something that returns formatted data, not a JavaScript asset.
- Caching and CDN usage.
- Different needs in the application. When I load the component for the editor (`fetch(ENDPOINT)`), I don't care at all for the raw JavaScript code. When I `import` it, I don't care at all for the `.vue` code and so on.

Specs for the API endpoint:

```js
// GET /api/components/ComponentId
const response = {
  id: ComponentId, // e.g., "localhost.MyComponent", or "USERNAME.MyComponent".
  name: String, // e.g., "MyComponent".
  sfc: String, // Code formatted to be used in editor (.vue).
  type: String, // "layout" or "default".
};

// PUT /api/components/ComponentId
const body = {
  id: ComponentId, // e.g., "localhost.MyComponent", or "USERNAME.MyComponent".
  name: String, // e.g., "MyComponent".
  sfc: String, // Code formatted to be used in editor (.vue).
  type: String, // "layout" or "default".
};

// POST /api/components
const body = {
  name: String, // e.g., "MyComponent".
  sfc: String, // Code formatted to be used in editor (.vue).
  type: String, // "layout" or "default".
};
```

`USERNAME.MyComponent` might be preferable because users might change their `host` at any time. Also, users have to type this in their code `USERNAME.MyComponent` might feel more natural.
Another possibility would be `SITE_NAME.MyComponent`. Maybe both is necessary. `USERNAME.MyComponent` for components that can be used across multiple sites and `SITE_NAME.MyComponent` for components specific to a site. If users can choose if their component is global or only available to a specific site, we need to add an additional field, e.g., `visibility: 'global|site'`.

**Comment by sparkyspider** [comment]
Hi Markus, some good point there. Here are my further thoughts:

1. I like that `/api/`  makes it really clear what is a page url and what is a component call.

    > `electronics.windflow.io/api/components/transistors` vs `electronics.windflow.io/components/transitors`
    >
    > (I'm not hell bent on this idea but it does also make it a little easier for Spring to differentiate)

2. I'm happy to use 2 seperate endpoints. Should we have `/api` and `/system/` rather?

3. I like the namespacing in the url. It makes it really clear to see what component / page belongs to what app (in browser console). It also makes faster for me to not to have to do a namespace lookup on the server (as a person can have multiple domains pointing to the siteId). We can add a header with the sideid (or I can add the aliases to the JWT) but why do we want to make more work for ourselves?

4. Regarding components, component names and namespaces.

    > It is important we can import components from other namespaces  (eg:)
    >
    > (marketplace.windflow.io/components/shopping-basket)
    >
    > This allows the component developer to sealmessly "upgrade" those components as they don't belong to the user. A user will use the `+` button in the toolbar to add the marketplace component to their page. As soon as they edit the component, the component needs to be copied into their namespace.
    > With regards to component names. I really prefer the idea of using friendly names so that the developer can easily remember them. They may also end up with several copies on the same component on a page (such as paragraph) so having names like IntroText, etc makes it really much easier. I think we can create reasonable defaults (using the component 'name' property in the source code) for stuff that has been copied and pasted, or added using the + from the component library.

5. I'm happy with your API.

**Comment by maoberlehner** [comment]
> 2. I'm happy to use 2 seperate endpoints. Should we have /api and /system/ rather?

Idk about `/system`. The URL is exposed to the users when they build their components. So when they want to import one of their custom components into another component they have to type `import MyCompoent from '/system/components/SOME_NAMESPACE/SOME_PREFIX.MyComponent.vue'`. Seems not very intuitive to me. But I also can see the problem with having too many reserved words the users can't use as sites. Maybe we should rewrite all `/components/...` imports to `components.windflow.io/...` when converting the `.vue` file? Than we don't need any reserved words. But from a technical point of view I'm fine with `/system`.

> 3. I like the namespacing in the url. It makes it really clear to see what component / page belongs to what app (in browser console). It also makes faster for me to not to have to do a namespace lookup on the server (as a person can have multiple domains pointing to the siteId). We can add a header with the sideid (or I can add the aliases to the JWT) but why do we want to make more work for ourselves?

I don't get this at all. Currently the namespace is the host. So when I build the URL like `/api/components/localhost/MyComponent.vue` I do it by taking the current host from the URL. If a site has multiple domains, I send you some of those possible hosts depending on which one is used to open the site. This is 100% exactly the same information you can get from the `Host` (or is `Referer` the correct one for that?) header. Idk if I'm completely having this backwards but I can't see how it is different to get it from the request header over sending it in the URL 🤔
It's not that big of a deal but I find it pretty strange that the URL for the same component changes depending on which Host is used. Also, if I have `o.net` and `oberlehner.net` pointing to the same site, then users can import the same component with  `import MyComponent from '/system/components/o/MyComponent.vue'` and `import MyComponent from '/system/components/oberlehner/MyComponent.vue'`. Weird.

What I just realize, maybe we are talking completely past each other: you can make the component ID whatever you want. So if you want the host or whatever as namespace, the component ID would probably be something like `localhost.MyComponent` like it is now. So the URL would be `/system/components/localhost.MyComponent.vue` and `/api/components/localhost.MyComponent` -> `localhost.MyComponent` is the ID.

> 4. Regarding components, component names and namespaces.

Not relevant for me on the frontend. I get ComponentID from the server and I load the component with the ID.

> Further thought: The server is stateless (it's unaware of what you did last, what request you pulled last time). Therefore, when you save a component (it's useful to the server if you can post it with the siteId that comes down with the page). This being said if this is really a problem for you, then I can add all the aliases in the JWT and then read the siteid/namespace out the JWT and store it with the component in the database. Fetching will be a little trickier as I don't know who's component we're using (someone from marketplace, or our own)

It's not really a problem to send the siteId but, again, I don't understand why this is useful? When POST I send you the JWT, with that you know which site the request/component belongs to, don't you?
When GET I send you a unique ID you sent me before, you can simple load the component with that ID from the database. To check if the current host is allowed to use it, you check if the `Referer` header matches one of the domains of the sites the component is linked to (or just let it through if it is a global component).
If I send you the siteId and you determine if the component is allowed to be rendered on that site, our users could just send manipulated siteids to render components which are restricted to certain sites.

As I already wrote, maybe I get something completely backwards, but as I currently understand it, there are a few things which just not make sense to me.

**Comment by sparkyspider** [comment]
Ok, what about this:

1. We push/pull pages json from `/api/pages/about` or `/api/pages/about/contact`
2. We push/pull user components (json containing vue) of the same site from `/api/components/ShoppingCart`
3. We pull 3rd party components (json containing vue) externally from `/api/components/woo.windflow.io/ShoppingCart`
4. The app pulls local js components from `/components/ShoppingCart.js`
5. The app pulls external js components from `/components/woo.windflow.io/ShoppingCart.js`

* `/api` and `/components` are reserved words

**Comment by maoberlehner** [comment]
I'm ok with that if you send me `woo.windflow.io/ShoppingCart` as the ID of the component.

```js
// GET /api/components/woo.windflow.io/ShoppingCart
const response = {
  id: 'woo.windflow.io/ShoppingCart',
  name: 'ShoppingCart',
  sfc: 'THE CODE',
  type: 'default',
};

// GET /api/pages/about/contact
const response = {
    // ...
    "areas": [
        {
            "area": "content",
            "components":[
                // Currently a little bit confusing because the id here is the chapter id
                // and the name is the component id. But this has no priority for me.
                {"name":"woo.windflow.io/ShoppingCart", "id":"7"},
            ]
        }
    ],
}
```

**Comment by sparkyspider** [comment]
Great accepted. Will close tomorrow when completed.

**Comment by sparkyspider** [comment]
Update...

1. We `get`/`put` page json content from `/api/pages/about` or `/api/pages/about/contact` (uses host header id)
2. We `get`/`put` same-site components (json containing .vue) from `/api/components/ShoppingCart` (host header)
**3. We `get`/`put` same-site layouts (json containing .vue) from `/api/layouts/ShoppingCart` (host header)**
4. We `get`/`put` 3rd party components (json containing .vue) from `/api/components/woo.windflow.io/ShoppingCart`
**5. We `get`/`put` 3rd party layouts (json containing .vue) from `/api/layouts/woo.windflow.io/ShoppingCart`**
6. The `get`'s pulls local js components from `/components/ShoppingCart.js` (uses host header to id)
7. The `get`'s pulls external js components from `/components/woo.windflow.io/ShoppingCart.js`

Update Conditions:

* `/api` and `/components` and *`/layouts`* are reserved words
* app can only pull its own pages.

**Comment by sparkyspider** [comment]
Hi Markus,

I created a pull request that you can merge if you like. Otherwise you can just checkout the branch. Obviousy as we've changed the URL's, these are breaking changes.

https://github.com/windflow-io/EternalEngine/pull/26/files (pull request) or
https://github.com/windflow-io/EternalEngine/tree/rest-api-refactor (branch)

The API is as follows:

Get: http://auth.windflow.io.local:8080/api/pages/
Get: http://auth.windflow.io.local:8080/components/GithubAuth.js
Get: http://auth.windflow.io.local:8080/components/auth-windflow-io.windflow.app.local/GithubAuth.js
Get: http://auth.windflow.io.local:8080/api/components/GithubAuth
Put: http://auth.windflow.io.local:8080/api/components
```json
{
    "name": "GithubHello",
    "sfc": "<template><h1>Welcome Home</h1></template>",
    "type": "COMPONENT",
    "id": "auth-windflow-io.windflow.app.local.GithubHello"
}
```

NB: Postman configuration can be downloaded and installed into postman here: https://www.postman.com/collections/9e0fc232c0fd9bd96f54

**Comment by sparkyspider** [comment]
Hi Markus,

1. Please can you refactor the client code to work with this API.
2. I've added exhaustive debugging code in for AUTH. Perhaps you'd like to investigate if the debug output gives you clues.
3. I can't test the debug code as I can't run the app at the moment (controllers broken due to refactor)
4. When it's up and riding again, see if anything comes to mind with regards to the auth problem, then let's solve it.

**Comment by maoberlehner** [comment]
You use two different ID formats:
`auth-windflow-io.windflow.app.local/GithubAuth.js` in `http://auth.windflow.io.local:8080/components/auth-windflow-io.windflow.app.local/GithubAuth.js`.
vs
`auth-windflow-io.windflow.app.local.GithubHello` in `"id": "auth-windflow-io.windflow.app.local.GithubHello"`

Would be very happy if you could make this uniform so I don't have to do any extra logic on the client. I just want to have an ID and no knowledge of namespaces whatsoever in the frontend code.

**Comment by maoberlehner** [comment]
Updated the frontend to match new APIs. But it does not work 100% yet
1. Because inconsistent ID, loading the components (`/components/system.windflow.io.CenteredLayout.js`) does not work.
2. Edit mode does not work because I get the following error, when trying to load a component from `/api/components/system.windflow.io.NotFoundDisplay`

```bash
errorCode: "ERROR_003"
errorDescription: "This domain has not been configured"
errorDetail: "ERROR_003: 404 Domain Not Configured: domain: localhost"
errorTitle: "404 Domain Not Configured"
httpStatus: 404
```

**Comment by sparkyspider** [comment]
Give me a few minutes :)

**Comment by sparkyspider** [comment]
Please see comments in commit. Should be all good now.

https://github.com/windflow-io/EternalEngine/commit/d42fee591272ffaddd5ddcb1f7a89939fcec0779

**Comment by sparkyspider** [comment]
@maoberlehner please note that there is no more `/layouts/`. There is only `/components/` as in `/components` eg: `/CenteredLayout.js`. Please also add a `eternalengine.siteOwnerGithubEmail=mark@flyh2.com` to your `secret.properties`
